Repository ita-social-projects/OoS-Backend, pull requests merged in 2022-06, with the labels that each got.

#661 Fix mapping
  OutOfSchool/OutOfSchool.WebApi/Extensions/MappingExtensions.cs
Labels: enhancement, backend

#672 made workshop filter to always sort by alphabet
  OutOfSchool/OutOfSchool.ElasticsearchData/ESWorkshopProvider.cs
Labels: bug:fixed

#676 rbiyovskiy/675 registration form sp no error messages in the email field
  OutOfSchool/OutOfSchool.Common/Constants.cs
  OutOfSchool/OutOfSchool.IdentityServer/Controllers/AuthController.cs
  OutOfSchool/OutOfSchool.IdentityServer/Resources/SharedResource.en.resx
  OutOfSchool/OutOfSchool.IdentityServer/Resources/SharedResource.uk.resx
  OutOfSchool/OutOfSchool.IdentityServer/ViewModels/RegisterViewModel.cs
Labels: backend

#679 Romanchuk / Add ordering to results
  OutOfSchool/OutOfSchool.WebApi/Services/SubordinationStructure/InstitutionHierarchyService.cs
Labels: enhancement, backend

#681 Romanchuk/Add Redis to institution hierarchy
  OutOfSchool/OutOfSchool.WebApi/Services/StatisticService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/SubordinationStructure/IInstitutionFieldDescriptionService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/SubordinationStructure/IInstitutionHierarchyService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/SubordinationStructure/IInstitutionService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/SubordinationStructure/InstitutionFieldDescriptionService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/SubordinationStructure/InstitutionHierarchyService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/SubordinationStructure/InstitutionService.cs
Labels: enhancement, backend

#593 Romanchuk Lukashov/Provider admin GRPC
  OutOfSchool/OutOfSchool.IdentityServer/Config/GRPCConfig.cs
  OutOfSchool/OutOfSchool.IdentityServer/OutOfSchool.IdentityServer.csproj
  OutOfSchool/OutOfSchool.IdentityServer/Properties/launchSettings.json
  OutOfSchool/OutOfSchool.IdentityServer/Services/ProviderAdminService.cs
  OutOfSchool/OutOfSchool.IdentityServer/Services/ProviderAdminServiceGRPC.cs
  OutOfSchool/OutOfSchool.IdentityServer/Startup.cs
  OutOfSchool/OutOfSchool.IdentityServer/Util/MappingProfile.cs
  OutOfSchool/OutOfSchool.IdentityServer/appsettings.json
  OutOfSchool/OutOfSchool.WebApi/Config/GRPCConfig.cs
  OutOfSchool/OutOfSchool.WebApi/OutOfSchool.WebApi.csproj
  OutOfSchool/OutOfSchool.WebApi/Services/GRPC/GRPCCommonService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/GRPC/IGRPCCommonService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderAdminOperations/IProviderAdminOperationsService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderAdminOperations/ProviderAdminOperationsGRPCService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderAdminOperations/ProviderAdminOperationsRESTService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderAdminService.cs
  OutOfSchool/OutOfSchool.WebApi/Startup.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
  OutOfSchool/OutOfSchool.WebApi/appsettings.json
  OutOfSchool/OutOfSchool.gRPC/OutOfSchool.gRPC.csproj
  OutOfSchool/OutOfSchool.gRPC/Protos/ProviderAdmin.proto
  OutOfSchool/OutOfSchool.sln
Labels: enhancement, backend

#702 Fix for creating Provider
  OutOfSchool/OutOfSchool.WebApi/Models/ProviderDto.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
Labels: backend, bug:fixed

#707 fixed mapping for the Provider.SectionName
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
Labels: backend, bug:fixed

#684 rbiyovskiy/680 implement codeficator service
  OutOfSchool/OutOfSchool.Common/Constants.cs
  OutOfSchool/OutOfSchool.Common/Models/CodeficatorAddressDto.cs
  OutOfSchool/OutOfSchool.DataAccess/Enums/CodeficatorCategory.cs
  OutOfSchool/OutOfSchool.DataAccess/Repository/CodeficatorRepository.cs
  OutOfSchool/OutOfSchool.DataAccess/Repository/ICodeficatorRepository.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/CodeficatorServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/CodeficatorController.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Codeficator/AllAddressPartsDto.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Codeficator/CodeficatorDto.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Codeficator/CodeficatorFilter.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Codeficator/CodeficatorWithParentDto.cs
  OutOfSchool/OutOfSchool.WebApi/Models/OffsetFilter.cs
  OutOfSchool/OutOfSchool.WebApi/Models/SizeFilter.cs
  OutOfSchool/OutOfSchool.WebApi/Services/CodeficatorService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ICodeficatorService.cs
  OutOfSchool/OutOfSchool.WebApi/Startup.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
Labels: enhancement, backend

#717 rbiyovskiy/715 fix test
  OutOfSchool/OutOfSchool.IdentityServer.Tests/Controllers/AuthControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ApplicationServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/WorkshopServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/QuartzTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ApplicationController.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
  OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/ApplicationDTOsGenerator.cs
Labels: bug, backend
