Repository ita-social-projects/OoS-Backend, pull requests merged in 2022-09, with the labels that each got.

#835 Fixed achivement delete
  OutOfSchool/OutOfSchool.WebApi/Services/AchievementService.cs
Labels: backend, bug:fixed

#832 Baditsa/add get workshop short card by provider
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/WorkshopControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/WorkshopServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/WorkshopController.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V2/WorkshopController.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Workshop/WorkshopCard.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/IWorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IWorkshopServicesCombiner.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderAdminService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/WorkshopServicesCombiner.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
Labels: enhancement

#851 Romanchuk/Add Workshop.Title to notification
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/WorkshopServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/WorkshopController.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Workshop/WorkshopStatusDto.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Workshop/WorkshopStatusWithTitleDto.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/IWorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/WorkshopServicesCombiner.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
Labels: enhancement, backend

#852 Romanchuk/Fix mapping
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
Labels: backend, bug:fixed

#853 Romanchuk/Update for ProviderAdmin was added
  OutOfSchool/OutOfSchool.Common/Models/UpdateProviderAdminDto.cs
  OutOfSchool/OutOfSchool.DataAccess/Enums/OperationType.cs
  OutOfSchool/OutOfSchool.IdentityServer/Controllers/ProviderAdminController.cs
  OutOfSchool/OutOfSchool.IdentityServer/Services/Interfaces/IProviderAdminService.cs
  OutOfSchool/OutOfSchool.IdentityServer/Services/ProviderAdminService.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ProviderAdminController.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Communication/CommunicationConstants.cs
  OutOfSchool/OutOfSchool.WebApi/Services/DirectionService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IProviderAdminService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderAdminService.cs
Labels: backend
