Repository ita-social-projects/OoS-Backend, pull requests merged in 2022-08, with the labels that each got.

#788 Baditsa/improve email templates
  OutOfSchool/OutOfSchool.EmailSender/DevEmailSender.cs
  OutOfSchool/OutOfSchool.EmailSender/EmailSender.cs
  OutOfSchool/OutOfSchool.EmailSender/IEmailSender.cs
  OutOfSchool/OutOfSchool.IdentityServer/Controllers/AccountController.cs
  OutOfSchool/OutOfSchool.IdentityServer/Services/MinistryAdminService.cs
  OutOfSchool/OutOfSchool.IdentityServer/Services/ProviderAdminService.cs
  OutOfSchool/OutOfSchool.RazorTemplatesData/Services/IRazorViewToStringRenderer.cs
  OutOfSchool/OutOfSchool.RazorTemplatesData/Services/RazorViewToStringRenderer.cs
  OutOfSchool/OutOfSchool.RazorTemplatesData/Views/Shared/EmailButton.cshtml
  OutOfSchool/OutOfSchool.RazorTemplatesData/Views/Shared/EmailLayout.cshtml
  OutOfSchool/OutOfSchool.RazorTemplatesData/wwwroot/images/Vector.png
Labels: backend

#790 Checking on null for user.MiddleName was added
  OutOfSchool/OutOfSchool.DataAccess/Repository/ParentRepository.cs
Labels: backend, bug:fixed

#787 rbiyovskiy/785 codeficator add ordering and city districts to the result of the search request
  OutOfSchool/OutOfSchool.Common/Constants.cs
  OutOfSchool/OutOfSchool.Common/Enums/CodeficatorCategory.cs
  OutOfSchool/OutOfSchool.Common/Models/CodeficatorAddressDto.cs
  OutOfSchool/OutOfSchool.Common/OutOfSchool.Common.csproj
  OutOfSchool/OutOfSchool.DataAccess/Models/Codeficator.cs
  OutOfSchool/OutOfSchool.DataAccess/OutOfSchool.DataAccess.csproj
  OutOfSchool/OutOfSchool.DataAccess/Repository/CodeficatorRepository.cs
  OutOfSchool/OutOfSchool.DataAccess/Repository/Config/CodeficatorUpdateOrder.sql
  OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/OutOfSchoolDbContextModelSnapshot.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/CodeficatorServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Models/AddressDto.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Codeficator/AllAddressPartsDto.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Codeficator/CodeficatorDto.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Codeficator/CodeficatorFilter.cs
  OutOfSchool/OutOfSchool.WebApi/Services/CodeficatorService.cs
Labels: enhancement, backend

#807 Add search string to ChangeLog filter
  OutOfSchool/OutOfSchool.WebApi/Models/Changes/ChangesLogFilterBase.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Changes/ProviderAdminChangesLogRequest.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ChangesLogService.cs
Labels: backend

#803 Add GetByFilter for MinistryAdmin
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/MinistryAdminController.cs
  OutOfSchool/OutOfSchool.WebApi/Models/MinistryAdminFilter.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IMinistryAdminService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/MinistryAdminService.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
Labels: enhancement, backend

#809 Fix some child's fixes :)
  OutOfSchool/OutOfSchool.WebApi/Services/ChildService.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
Labels: bug:fixed

#813 Add endpoints
  OutOfSchool/OutOfSchool.IdentityServer/db-scripts.txt
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ChildController.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/WorkshopController.cs
  OutOfSchool/OutOfSchool.WebApi/Models/ShortEntityDto.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ChildService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/IWorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IChildService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IWorkshopServicesCombiner.cs
  OutOfSchool/OutOfSchool.WebApi/Services/WorkshopServicesCombiner.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
Labels: backend

#815 Checking email when MinistryAdmin is created
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/MinistryAdminController.cs
  OutOfSchool/OutOfSchool.WebApi/Services/MinistryAdminService.cs
Labels: backend, bug:fixed

#825 Add WorkshopViewProviderCard
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/WorkshopControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/WorkshopServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/WorkshopController.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Workshop/WorkshopCard.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/IWorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IProviderAdminService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IWorkshopServicesCombiner.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderAdminService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/WorkshopServicesCombiner.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
  OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/WorkshopBaseCardGenerator.cs
Labels: enhancement

#829 Fix error
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ChildController.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ChildService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IChildService.cs
Labels: backend, bug:fixed

#831 Uncomment
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ChildController.cs
Labels: bug:fixed
