Repository ita-social-projects/OoS-Backend, pull requests merged in 2022-02, with the labels that each got.

#534 #530 Romanchuk lukashov/deletion direction department class
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/ClassControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/DepartmentControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/DirectionControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ClassServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/DepartmentServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/DirectionServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ClassController.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/DepartmentController.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/DirectionController.cs
  OutOfSchool/OutOfSchool.WebApi/Resources/SharedResource.en.resx
  OutOfSchool/OutOfSchool.WebApi/Resources/SharedResource.uk.resx
  OutOfSchool/OutOfSchool.WebApi/Services/ClassService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/DepartmentService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/DirectionService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IClassService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IDepartmentService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IDirectionService.cs
Labels: enhancement, backend

#533 #790 Issue in Frontend project.
  OutOfSchool/OutOfSchool.IdentityServer/Controllers/AuthController.cs
  OutOfSchool/OutOfSchool.IdentityServer/Resources/SharedResource.uk.resx
  OutOfSchool/OutOfSchool.IdentityServer/Startup.cs
  OutOfSchool/OutOfSchool.IdentityServer/ViewModels/RegisterViewModel.cs
Labels: bug, backend

#544 Header "Access-Control-Allow-Headers" for response StatusCode was added.
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ApplicationController.cs
Labels: bug, backend

#546 Change header
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ApplicationController.cs
Labels: enhancement, backend

#567 Fix
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ApplicationServiceTests.cs
Labels: bug, backend

#569 Romanchuk lukashov/fix logout redirect
  OutOfSchool/OutOfSchool.IdentityServer.Tests/Controllers/AuthControllerTests.cs
  OutOfSchool/OutOfSchool.IdentityServer/Config/IdentityServerConfig.cs
  OutOfSchool/OutOfSchool.IdentityServer/Controllers/AuthController.cs
  OutOfSchool/OutOfSchool.IdentityServer/appsettings.Google.json
  OutOfSchool/OutOfSchool.IdentityServer/appsettings.json
Labels: backend, bug:fixed
