Repository ita-social-projects/OoS-Backend, pull requests merged in 2022-01, with the labels that each got.

#489 Fix tests
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/ChildControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/WorkshopControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/StatisticServiceTest.cs
  OutOfSchool/OutOfSchool.WebApi/Models/ParentCard.cs
  OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/ChildDtoGenerator.cs
Labels: backend

#491 #488 Functionality for getting the nearest city by latitude and longitude
  OutOfSchool/OutOfSchool.Common/GeoMathHelper.cs
  OutOfSchool/OutOfSchool.DataAccess/Models/City.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/CityController.cs
  OutOfSchool/OutOfSchool.WebApi/Extensions/GeoMathHelperExtensions.cs
  OutOfSchool/OutOfSchool.WebApi/Models/CityFilter.cs
  OutOfSchool/OutOfSchool.WebApi/Services/CityService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ICityService.cs
Labels: enhancement, backend

#497 Got rid of the CreateMultiple applications method
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/ApplicationControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ApplicationServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/ApiModels/ApplicationApiModel.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ApplicationController.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ApplicationService.cs
Labels: backend

#492 #254 SupportInformation functionality was added.
  OutOfSchool/OutOfSchool.DataAccess/Models/SupportInformation.cs
  OutOfSchool/OutOfSchool.DataAccess/OutOfSchoolDbContext.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/SupportInformationController.cs
  OutOfSchool/OutOfSchool.WebApi/Models/SupportInformationDto.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ISupportInformationService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/SupportInformationService.cs
  OutOfSchool/OutOfSchool.WebApi/Startup.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
Labels: enhancement, backend

#504 #490 Change status code if user exceeds the application limit
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/ApplicationControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ApplicationServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Config/ApplicationsConstraintsConfig.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ApplicationController.cs
  OutOfSchool/OutOfSchool.WebApi/Extensions/ExceptionMiddlewareExtension.cs
  OutOfSchool/OutOfSchool.WebApi/Models/ModelWithAdditionalData.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ApplicationService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IApplicationService.cs
  OutOfSchool/OutOfSchool.WebApi/Startup.cs
  OutOfSchool/OutOfSchool.WebApi/appsettings.json
Labels: enhancement, backend

#524 #144 Logging and localization for exceptions were added.
  OutOfSchool/OutOfSchool.WebApi.Tests/Hubs/ChatWorkshopHubTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ChatWorkshopController.cs
  OutOfSchool/OutOfSchool.WebApi/Hubs/ChatWorkshopHub.cs
  OutOfSchool/OutOfSchool.WebApi/Resources/SharedResource.en.resx
  OutOfSchool/OutOfSchool.WebApi/Resources/SharedResource.uk.resx
Labels: enhancement, backend

#531 Fix some bugs in ApplicationTests
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/ApplicationControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ApplicationServiceTests.cs
Labels: bug, backend
