Repository ita-social-projects/OoS-Backend, pull requests merged in 2022-07, with the labels that each got.

#705 Romanchuk/Add pagination and filter
  OutOfSchool/OutOfSchool.Common/Extensions/StringExtensions.cs
  OutOfSchool/OutOfSchool.DataAccess/Repository/EntityRepositoryBase.cs
  OutOfSchool/OutOfSchool.DataAccess/Repository/IEntityRepository.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ApplicationServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ChangesLogServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ClassServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/WorkshopServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/InstitutionHierarchyServiceTest.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ProviderServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/StatisticServiceTest.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ParentController.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ProviderController.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Providers/ProviderFilter.cs
  OutOfSchool/OutOfSchool.WebApi/Models/SearchStringFilter.cs
  OutOfSchool/OutOfSchool.WebApi/Services/AchievementService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ApplicationService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ChangesLogService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ChatMessageWorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ChatRoomWorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ChildService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ClassService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/DepartmentService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/DirectionService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/FavoriteService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IParentService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ParentService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/StatisticService.cs
  OutOfSchool/OutOfSchool.WebApi/Util/IPaginationHelper.cs
  OutOfSchool/OutOfSchool.WebApi/Util/PaginationHelper.cs
Labels: enhancement, backend

#703 rbiyovskiy/689 we receive provider subrole in token it could be either deputy pr provideradmin
  OutOfSchool/OutOfSchool.Common/Models/CreateProviderAdminDto.cs
  OutOfSchool/OutOfSchool.DataAccess/Repository/ProviderAdminRepository.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ApplicationController.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ProviderAdminController.cs
  OutOfSchool/OutOfSchool.WebApi/Models/ProviderAdminDto.cs
  OutOfSchool/OutOfSchool.WebApi/Models/ProviderAdminProviderRelationDto.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ApplicationService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IApplicationService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IProviderAdminService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderAdminService.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
Labels: bug, enhancement, backend

#723 Some fixes
  OutOfSchool/OutOfSchool.DataAccess/Repository/IEntityRepository.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ApplicationServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ChangesLogServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ApplicationService.cs
Labels: backend, bug:fixed

#724 Fix providers update NRE
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ProviderServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderService.cs
Labels: bug

#721 rbiyovskiy/718 applicationgetbyparentid add filter by childid
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ApplicationServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Models/ApplicationFilter.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ApplicationService.cs
Labels: enhancement, backend

#694 Baditsa/changing workshops status
  OutOfSchool/OutOfSchool.Common/Enums/WorkshopStatus.cs
  OutOfSchool/OutOfSchool.ElasticsearchData/ESWorkshopProvider.cs
  OutOfSchool/OutOfSchool.ElasticsearchData/Models/WorkshopES.cs
  OutOfSchool/OutOfSchool.ElasticsearchData/Models/WorkshopFilterES.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/WorkshopControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ApplicationServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/WorkshopServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/WorkshopController.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V2/WorkshopController.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Workshop/WorkshopCard.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Workshop/WorkshopFilter.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Workshop/WorkshopStatusDto.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ApplicationService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/IWorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IWorkshopServicesCombiner.cs
  OutOfSchool/OutOfSchool.WebApi/Services/WorkshopServicesCombiner.cs
  OutOfSchool/OutOfSchool.WebApi/Services/WorkshopServicesCombinerV2.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
Labels: backend

#730 Romanchuk/Add filtering to get children
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/ChildControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Extensions/MappingExtensionsTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ChildController.cs
  OutOfSchool/OutOfSchool.WebApi/Extensions/MappingExtensions.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ChildService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IChildService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ParentService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderService.cs
Labels: backend

#744 Fixes after sonar check
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/ChildControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ChildController.cs
  OutOfSchool/OutOfSchool.WebApi/Extensions/MappingExtensions.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ChildService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IChildService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ParentService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderService.cs
Labels: backend

#741 Bug fix
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
Labels: bug:fixed

#753 Fix tests
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/WorkshopControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/WorkshopController.cs
Labels: backend

#750 Baditsa/some improvements
  OutOfSchool/OutOfSchool.Common/Constants.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/WorkshopController.cs
  OutOfSchool/OutOfSchool.WebApi/Models/ApplicationDTO.cs
  OutOfSchool/OutOfSchool.WebApi/Models/ChildDTO.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Notifications/NotificationDto.cs
  OutOfSchool/OutOfSchool.WebApi/Models/ProviderAdminDto.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Providers/ProviderDto.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Providers/ProviderLicenseStatusDto.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Providers/ProviderStatusDto.cs
  OutOfSchool/OutOfSchool.WebApi/Models/RatingDTO.cs
  OutOfSchool/OutOfSchool.WebApi/Models/ShortApplicationDTO.cs
  OutOfSchool/OutOfSchool.WebApi/Models/ShortUserDto.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Teachers/TeacherDTO.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Workshop/WorkshopDTO.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Workshop/WorkshopStatusDto.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
Labels: backend

#759 AllowedToReview was added to application controller
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ApplicationController.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ApplicationService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IApplicationService.cs
Labels: backend

#761 Romanchuk/Add default size to size filter
  OutOfSchool/OutOfSchool.WebApi/Models/SizeFilter.cs
Labels: backend, bug:fixed

#765 Changes to Provider Get filter
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderService.cs
Labels: backend

#768 Baditsa/add a style in liner for e mail
  OutOfSchool/OutOfSchool.RazorTemplatesData/Views/Shared/EmailButton.cshtml
  OutOfSchool/OutOfSchool.RazorTemplatesData/Views/Shared/EmailLayout.cshtml
  OutOfSchool/OutOfSchool.RazorTemplatesData/wwwroot/css/site.css
Labels: backend

#774 rbiyovskiy/773 bug statisticgetworkshops
  OutOfSchool/OutOfSchool.WebApi/Models/Codeficator/AllAddressPartsDto.cs
Labels: bug, backend

#771 Romanchuk/Add IsRewiewed to rating controller
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ApplicationController.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/RatingController.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ApplicationService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IApplicationService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IRatingService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/RatingService.cs
Labels: backend

#777 Fix image path and styles
  OutOfSchool/OutOfSchool.RazorTemplatesData/Views/Emails/ResetPassword/ResetPassword.cshtml
  OutOfSchool/OutOfSchool.RazorTemplatesData/Views/Shared/EmailButton.cshtml
  OutOfSchool/OutOfSchool.RazorTemplatesData/Views/Shared/EmailLayout.cshtml
Labels: backend
