Repository ita-social-projects/OoS-Backend, pull requests merged in 2022-12, with the labels that each got.

#933 Romanchuk/Add EmailConfirmed to ParentDto model
  OutOfSchool/OutOfSchool.WebApi/Models/ParentDtoWithContactInfo.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
Labels: backend

#940 Romanchuk/Fix rating GetAllByEntityId
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/RatingController.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IRatingService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/RatingService.cs
Labels: backend, bug:fixed

#941 Update working hours bugfix
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/WorkshopServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs
Labels: bug:fixed

#953 Romanchuk / Fix geocoding mapping
  OutOfSchool/OutOfSchool.WebApi/Services/CodeficatorService.cs
Labels: backend, bug:fixed

#952 Romanchuk / Add mailing that the message has been read
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ChatMessageWorkshopServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ChatMessageWorkshopService.cs
Labels: backend

#956 Romanchuk / Return messages with chats
  OutOfSchool/OutOfSchool.DataAccess/Repository/ChatRoomWorkshopModelForChatListRepository.cs
  OutOfSchool/OutOfSchool.DataAccess/Repository/IChatRoomWorkshopModelForChatListRepository.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ChatWorkshopController.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ChatRoomWorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IChatRoomWorkshopService.cs
Labels: backend
