Repository ita-social-projects/OoS-Backend, pull requests merged in 2023-04, with the labels that each got.

#1034 Fix soft delete for provider
  OutOfSchool/OutOfSchool.DataAccess/Repository/IProviderRepository.cs
  OutOfSchool/OutOfSchool.DataAccess/Repository/ProviderRepository.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ProviderServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderService.cs
Labels: enhancement

#1045 Up CsvHelper version
  OutOfSchool/OutOfSchool.DataAccess/OutOfSchool.DataAccess.csproj
  OutOfSchool/OutOfSchool.WebApi/OutOfSchool.WebApi.csproj
  OutOfSchool/OutOfSchool.WebApi/Services/StatisticReports/StatisticReportsMakingService.cs
Labels: enhancement, backend

#1055 Romanchuk / Fix popular directions
  OutOfSchool/OutOfSchool.WebApi/Services/StatisticService.cs
Labels: backend, bug:fixed

#1061 Tsylia/ Fix average ratings calculating.
  OutOfSchool/OutOfSchool.WebApi/Services/AverageRatings/AverageRatingService.cs
Labels: backend, bug:fixed
