Repository ita-social-projects/OoS-Backend, pull requests merged in 2023-05, with the labels that each got.

#1083 Tsylia/ Fixed DateTime picker align and checkboxes labels align…
  OutOfSchool/OutOfSchool.IdentityServer/wwwroot/css/site.css
Labels: backend, bug:fixed

#1081 Baditsa/fix direction filter
  OutOfSchool/OutOfSchool.IdentityServer/Controllers/AccountController.cs
  OutOfSchool/OutOfSchool.RazorTemplatesData/Views/Emails/ConfirmEmail/ConfirmEmail.cshtml
  OutOfSchool/OutOfSchool.WebApi/Models/DirectionFilter.cs
  OutOfSchool/OutOfSchool.WebApi/Services/DirectionService.cs
Labels: backend, bug:fixed

#1082 Romanchuk / Change email
  OutOfSchool/OutOfSchool.IdentityServer/Controllers/AccountController.cs
  OutOfSchool/OutOfSchool.IdentityServer/Resources/SharedResource.en.resx
  OutOfSchool/OutOfSchool.IdentityServer/Resources/SharedResource.uk.resx
  OutOfSchool/OutOfSchool.IdentityServer/Views/Account/Email/SendChangeEmail.cshtml
Labels: backend, bug:fixed

#1099 Checking was added
  OutOfSchool/OutOfSchool.DataAccess/Repository/IWorkshopRepository.cs
  OutOfSchool/OutOfSchool.DataAccess/Repository/WorkshopRepository.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/ApplicationControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ApplicationServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ApplicationController.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ApplicationService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IApplicationService.cs
Labels: backend

#1104 Add token provider
  OutOfSchool/OutOfSchool.IdentityServer/Extensions/ConfigureIdentityExtensions.cs
Labels: bug:fixed

#1105 Add login link on ResetPasswordConfirmation page
  OutOfSchool/OutOfSchool.IdentityServer.Tests/Controllers/AccountControllerTests.cs
  OutOfSchool/OutOfSchool.IdentityServer/Controllers/AccountController.cs
  OutOfSchool/OutOfSchool.IdentityServer/Views/Account/Password/ResetPasswordConfirmation.cshtml
Labels: bug:fixed

#1108 Fix update of workshop
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/WorkshopServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs
Labels: backend, bug:fixed

#1110 Fix creating migrations
  OutOfSchool/OutOfSchool.IdentityServer/Extensions/ConfigureIdentityExtensions.cs
  OutOfSchool/OutOfSchool.IdentityServer/Startup.cs
Labels: backend, bug:fixed

#1086 Tsylia/ Add providers search by email and phone.
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderService.cs
Labels: backend, bug:fixed

#1113 Fix ProviderOwnership bug on workshop creating
  OutOfSchool/OutOfSchool.DataAccess/Repository/WorkshopRepository.cs
Labels: bug:fixed

#1116 Fix email confirmation
  OutOfSchool/OutOfSchool.IdentityServer/Services/ProviderAdminService.cs
Labels: backend, bug:fixed
