Repository ita-social-projects/OoS-Backend, pull requests merged in 2023-02, with the labels that each got.

#985 Getting short workshops list by ProviderAdminId
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/WorkshopServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/WorkshopController.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/IWorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/IWorkshopServicesCombiner.cs
  OutOfSchool/OutOfSchool.WebApi/Services/WorkshopServicesCombiner.cs
Labels: backend

#999 Romanchuk / Fix trigger's migration
  OutOfSchool/OutOfSchool.IdentityServer/Data/Migrations/OutOfSchoolMigrations/20230127121701_AddCodeficatorParentsTable.cs
Labels: backend, bug:fixed

#1004 Don't show blocked workshops in statistic (popular)
  OutOfSchool/OutOfSchool.WebApi/Services/StatisticService.cs
Labels: backend

#1000 Nazar yavor26/service provider statuses #955 and #969
  OutOfSchool/OutOfSchool.Common/Enums/ProviderStatus.cs
  OutOfSchool/OutOfSchool.DataAccess/Models/Configurations/ProviderConfiguration.cs
  OutOfSchool/OutOfSchool.ElasticsearchData/ESWorkshopProvider.cs
  OutOfSchool/OutOfSchool.ElasticsearchData/Models/WorkshopES.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/ProviderControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ProviderServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Providers/ProviderFilter.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Providers/ProviderStatusDto.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Workshop/WorkshopDTO.cs
  OutOfSchool/OutOfSchool.WebApi/Services/Database/WorkshopService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderServiceV2.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
  OutOfSchool/Tests/OutOfSchool.WebApi.IntegrationTests/ProviderServiceIntergrationTests/ProviderServiceUpdate.cs
Labels: backend

#1007 Add transaction to blocking Provider
  OutOfSchool/OutOfSchool.DataAccess/Repository/EntityRepositoryBase.cs
  OutOfSchool/OutOfSchool.DataAccess/Repository/IEntityRepository.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ProviderServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderService.cs
Labels: backend

#1013 Fixed namespace for ProviderStatus in FavoriveService
  OutOfSchool/OutOfSchool.WebApi/Services/FavoriteService.cs
Labels: bug:fixed
