Repository ita-social-projects/OoS-Backend, pull requests merged in 2024-04, with the labels that each got.

#1427 Fix notifications for deleting workshop
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ApplicationServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/BlockedProviderParentServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/InstitutionHierarchyServiceTest.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/LicenseApprovalNotificationServiceTest.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/NotificationServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ProviderServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ProviderServicesTests/PrivateProviderServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ProviderServicesTests/ProviderServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ProviderServicesTests/ProviderServiceV2Tests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ProviderServicesTests/PublicProviderServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/WorkshopServicesCombinerTests.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ApplicationService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/BlockedProviderParentService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/INotificationReciever.cs
  OutOfSchool/OutOfSchool.WebApi/Services/INotificationService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/LicenseApprovalNotification/LicenseApprovalNotificationService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/NotificationService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderServices/PrivateProviderService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderServices/ProviderService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderServices/PublicProviderService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/WorkshopServicesCombiner.cs
Labels: backend, bug:fixed

#1425 Vladp/add default roles initialization
  OutOfSchool/OutOfSchool.AuthCommon/Services/IdentityRolesInitializerHostedService.cs
  OutOfSchool/OutOfSchool.AuthCommon/Util/IdentityRolesCreator.cs
  OutOfSchool/OutOfSchool.AuthServer.Tests/Services/IdentityRolesInitializerHostedServiceTests.cs
  OutOfSchool/OutOfSchool.AuthorizationServer/Startup.cs
Labels: backend

#1436 Add validation exists Edrpou and Emails for providers
  OutOfSchool/OutOfSchool.DataAccess/Repository/IProviderRepository.cs
  OutOfSchool/OutOfSchool.DataAccess/Repository/ProviderRepository.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/AdminControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/ProviderRepositoryTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ProviderServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/AdminController.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Providers/ImportDataValidate.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ISensitiveProviderService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderServices/ProviderService.cs
  OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/ProvidersGenerator.cs
Labels: backend

#1412 Tsylia/1404_PasswordRecoveryCrossEye
  OutOfSchool/OutOfSchool.AuthCommon/Views/Account/Password/ResetPassword.cshtml
Labels: backend, bug:fixed

#1440 Add feature flag "TechAdminImport"
  OutOfSchool/OutOfSchool.WebApi/Config/FeatureManagementConfig.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/AdminController.cs
  OutOfSchool/OutOfSchool.WebApi/Enums/Feature.cs
  OutOfSchool/OutOfSchool.WebApi/appsettings.json
Labels: backend

#1438 Vladp/add export providers feature
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/AdminControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ProviderServicesTests/ProviderServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Config/FeatureManagementConfig.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/AdminController.cs
  OutOfSchool/OutOfSchool.WebApi/Enums/Feature.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Providers/ProviderCsvDto.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ISensitiveProviderService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderServices/ProviderService.cs
  OutOfSchool/OutOfSchool.WebApi/Util/MappingProfile.cs
  OutOfSchool/OutOfSchool.WebApi/appsettings.json
Labels: backend

#1443 Fix validation for emails
  OutOfSchool/OutOfSchool.DataAccess/Repository/ProviderRepository.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/ProviderRepositoryTests.cs
  OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/ProvidersGenerator.cs
Labels: backend, bug:fixed

#1454 Change import data validation
  OutOfSchool/OutOfSchool.DataAccess/Repository/IProviderRepository.cs
  OutOfSchool/OutOfSchool.DataAccess/Repository/ProviderRepository.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/AdminControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/ProviderRepositoryTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ProviderServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/AdminController.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Providers/ImportDataValidate.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Providers/ImportDataValidateRequest.cs
  OutOfSchool/OutOfSchool.WebApi/Models/Providers/ImportDataValidateResponse.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ISensitiveProviderService.cs
  OutOfSchool/OutOfSchool.WebApi/Services/ProviderServices/ProviderService.cs
Labels: backend

#1453 Fix changing of achievement's teachers
  OutOfSchool/OutOfSchool.DataAccess/Repository/AchievementRepository.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/Database/AchievementRepositoryTests.cs
  OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/AchievementGenerator.cs
  OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/AchievementTeacherGenerator.cs
  OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/AchievementTypeGenerator.cs
Labels: backend, bug:fixed

#1455 fix quartz DI
  OutOfSchool/OutOfSchool.AuthServer.Tests/EmailSender/EmailSenderServiceTests.cs
  OutOfSchool/OutOfSchool.AuthorizationServer/Extensions/QuartzExtension.cs
  OutOfSchool/OutOfSchool.EmailSender/Services/EmailSenderService.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Extensions/ServiceProviderExtensionsTests.cs
  OutOfSchool/OutOfSchool.WebApi/Extensions/Startup/QuartzExtension.cs
Labels: priority:critical

#1463 Remove redundant fields from register and age validation
  OutOfSchool/OutOfSchool.AuthCommon/Controllers/AuthController.cs
  OutOfSchool/OutOfSchool.AuthCommon/Extensions/AuthCommonServiceExtensions.cs
  OutOfSchool/OutOfSchool.AuthCommon/Validators/RegisterViewModelValidator.cs
  OutOfSchool/OutOfSchool.AuthCommon/ViewModels/RegisterViewModel.cs
  OutOfSchool/OutOfSchool.AuthCommon/Views/Auth/Register.cshtml
  OutOfSchool/OutOfSchool.AuthServer.Tests/Controllers/AuthControllerTests.cs
  OutOfSchool/OutOfSchool.Common/Constants.cs
  OutOfSchool/OutOfSchool.Common/Validators/CustomAgeAttribute.cs
  OutOfSchool/OutOfSchool.Common/Validators/CustomPhoneNumberAttribute.cs
  OutOfSchool/OutOfSchool.DataAccess/Models/Parent.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Models/ParentDraftCreationTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Validators/CustomAgeAttributeTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Validators/CustomPhoneNumberAttributeTests.cs
  OutOfSchool/OutOfSchool.WebApi/Models/ShortUserDto.cs
Labels: backend
