Repository ita-social-projects/OoS-Backend, pull requests merged in 2025-06, with the labels that each got.

#1848 create statistic endpoint + service methods to get popular competitions
  OutOfSchool/OutOfSchool.BusinessLogic/Services/IStatisticService.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Services/StatisticService.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/StatisticServiceTest.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/CompetitiveEventController.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/StatisticController.cs
Labels: backend

#1857 Fix AllowedToReview logic
  OutOfSchool/OutOfSchool.BusinessLogic/Services/ApplicationService.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ApplicationServiceTests.cs
Labels: enhancement, bug:fixed

#1862 Fix: EnumCollectionModelBinder returns null for empty values instead of empty HashSet
  OutOfSchool/OutOfSchool.WebApi.Tests/Util/EnumCollectionModelBinderTests.cs
  OutOfSchool/OutOfSchool.WebApi/Util/ModelBinding/EnumCollectionModelBinder.cs
Labels: bug:fixed

#1790 [Task] create thumbnail processing service
  OutOfSchool/OutOfSchool.BusinessLogic/Models/ThumbnailGenerationOptions.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Services/ThumbnailProcessor/IThumbnailProcessingService.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Services/ThumbnailProcessor/ThumbnailProcessingService.cs
  OutOfSchool/OutOfSchool.Common/Constants.cs
  OutOfSchool/OutOfSchool.DataAccess/Repository/Files/FileInDbStorageBase.cs
  OutOfSchool/OutOfSchool.ExternalFileStore.Api/IFilesStorage.cs
  OutOfSchool/OutOfSchool.ExternalFileStore.Api/IMetadataStorage.cs
  OutOfSchool/OutOfSchool.ExternalFileStore.Impl/FakeImplementations/FakeFilesStorageBase.cs
  OutOfSchool/OutOfSchool.ExternalFileStore.Impl/FilesStorageBase.cs
  OutOfSchool/OutOfSchool.ExternalFileStore.Impl/Gcs/GcpFilesStorageBase.cs
  OutOfSchool/OutOfSchool.ExternalFileStore.Impl/S3/S3FilesStorageBase.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ThumbnailProcessingServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/ThumbnailTestController.cs
  OutOfSchool/OutOfSchool.WebApi/Startup.cs
  OutOfSchool/OutOfSchool.WebApi/appsettings.json
Labels: enhancement, backend
