Repository ita-social-projects/OoS-Backend, pull requests merged in 2025-05, with the labels that each got.

#1824 fix(filters): Filtering Workshops by Payment Type
  OutOfSchool/OutOfSchool.BusinessLogic/Models/Workshops/WorkshopFilter.cs
Labels: backend, sev:critical, bug:fixed

#1839 Implement Moderator Edit Functionality for Workshop Drafts
  OutOfSchool/OutOfSchool.BusinessLogic/Common/Result.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Extensions/WorkshopDraftContentExtensions.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Models/Changes/ChangesLogFilter.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Models/Changes/WorkshopDraftChangesLogDto.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Models/Changes/WorkshopDraftChangesLogRequest.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Models/WorkshopDraft/ModeratorWorkshopDraftEditDto.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Services/ChangesLogService.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Services/CurrentUserService.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Services/IChangesLogService.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Services/Logging/CollectionChangeLogger.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Services/Logging/ICollectionChangeLogger.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Services/Logging/INestedObjectChangeLogger.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Services/Logging/NestedObjectChangeLogger.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Services/ValueProjector.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Services/WorkshopDrafts/ISensitiveWorkshopDraftService.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Services/WorkshopDrafts/WorkshopDraftService.cs
  OutOfSchool/OutOfSchool.Common/Models/UserRights.cs
  OutOfSchool/OutOfSchool.Common/PermissionModule/PermissionManagement/PermissionsSeeder.cs
  OutOfSchool/OutOfSchool.DataAccess/Enums/WorkshopStatus/WorkshopDraftStatus.cs
  OutOfSchool/OutOfSchool.DataAccess/Repository/Api/IChangesLogRepository.cs
  OutOfSchool/OutOfSchool.DataAccess/Repository/ChangesLogRepository.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/ChangeLogControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Controllers/WorkshopDraftControllerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Extensions/ToActionResultExtensionTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/ChangesLogServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/CollectionChangeLoggerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/NestedObjectChangeLoggerTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/SensitiveWorkshopDraftServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/WorkshopDraftServiceTests.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V1/ChangesLogController.cs
  OutOfSchool/OutOfSchool.WebApi/Controllers/V2/WorkshopDraftController.cs
  OutOfSchool/OutOfSchool.WebApi/Extensions/ControllerExtension.cs
  OutOfSchool/OutOfSchool.WebApi/Startup.cs
  OutOfSchool/OutOfSchool.WebApi/appsettings.json
  OutOfSchool/Tests/OutOfSchool.WebApi.IntegrationTests/ChangeLogControllerTests/ChangeLogControllerTests.cs
Labels: priority:high, new scope, pre-release

#1842 Updated position filtering logic
  OutOfSchool/OutOfSchool.BusinessLogic/Models/Position/PositionsFilter.cs
  OutOfSchool/OutOfSchool.BusinessLogic/Services/PositionService.cs
  OutOfSchool/OutOfSchool.WebApi.Tests/Services/PositionServiceTests.cs
Labels: enhancement, backend

#1846 Fixed a bug with saving a WorkshopDraft after editing related to mapping
  OutOfSchool/OutOfSchool.BusinessLogic/Models/Workshops/WorkshopV2Dto.cs
Labels: priority:high, bug:fixed, needs review, pre-release
